version: "0.2"
ignorePaths:
  - .git
  - .gitignore
  - "**/target"
  - "**/migrations"
dictionaryDefinitions: []
dictionaries: []
words:
  - axum
  - cargo
  - chrono
  - clippy
  - devcontainer
  - dnsutils
  - esac
  - mcpjson
  - postgres
  - postgresql
  - rustlang
  - serde
  - serde_json
  - sqlx
  - thiserror
  - tokio
  - trixie
  - uuid
ignoreWords: []
import: []
