version: "0.2"
ignorePaths:
  - .git
  - .gitignore
  - "**/target"
  - "**/migrations"
dictionaryDefinitions: []
dictionaries: []
words:
  - axum
  - clippy
  - sqlx
  - tokio
  - serde
  - serde_json
  - uuid
  - postgres
  - postgresql
  - rustlang
  - cargo
  - devcontainer
  - mcpjson
ignoreWords: []
import: []
